version: "3.8"

services:
  server:
    build:
      context: .
      target: dev
    ports:
      - ${PORT}:8080
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
